### ISSUE TITLE
merge_attrs fails on tag with string interpolation

### ISSUE THREAD

**Issue by smpallen99** [smpallen99/xain#9]
@romul  The following test case fails

``` elixir
  test ".class with nested element" do
    field_name = "id"
    result = th(".sortable.th-#{field_name}") do
      a "Id", href: "#test"
    end
    assert result = ~s(<th class="one two-2"><a href="#test">Id</a></th>)
  end
```

with the error below. I believe its due to the string interpolation appearing in the AST. 

```
  1) test .class with nested element (XainTest)
     test/xain_test.exs:282
     ** (FunctionClauseError) no function clause matching in Keyword.merge/2
     stacktrace:
       (elixir) lib/keyword.ex:545: Keyword.merge([], ".sortable.th-id")
       (xain) lib/xain.ex:128: Xain.merge_attrs/3
       (xain) lib/xain.ex:121: Xain.build_tag/5
       test/xain_test.exs:284
```

**Comment by romul** [comment]
@smpallen99 It was because calculated parameter was treated as `args`. Fixed in #10
